from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import io
import re
from datetime import datetime

def create_strategy_document(strategy_content: str) -> io.BytesIO:
    """
    Generates a professional Word document from the provided strategy markdown content.
    """
    doc = Document()
    
    # --- Styles ---
    # Customize Normal style
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # Custom Title Style
    if 'Title' in doc.styles:
        title_style = doc.styles['Title']
        title_style.font.name = 'Helvetica'
        title_style.font.size = Pt(26)
        title_style.font.bold = True
        title_style.font.color.rgb = RGBColor(0, 51, 102) # Dark Blue

    # Custom Heading 1
    h1_style = doc.styles['Heading 1']
    h1_style.font.name = 'Helvetica'
    h1_style.font.size = Pt(18)
    h1_style.font.color.rgb = RGBColor(0, 51, 102)
    h1_style.paragraph_format.space_before = Pt(24)
    h1_style.paragraph_format.space_after = Pt(12)

    # Custom Heading 2
    h2_style = doc.styles['Heading 2']
    h2_style.font.name = 'Helvetica'
    h2_style.font.size = Pt(14)
    h2_style.font.color.rgb = RGBColor(51, 102, 153) # Lighter Blue
    h2_style.paragraph_format.space_before = Pt(18)
    h2_style.paragraph_format.space_after = Pt(6)

    # --- Cover Page ---
    section = doc.sections[0]
    # Center the content vertically (approximation via newlines for simplicity)
    for _ in range(5):
        doc.add_paragraph()
    
    title_para = doc.add_paragraph("Enterprise AI Strategy Roadmap", style='Title')
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    subtitle_para = doc.add_paragraph("Strategic Transformation Plan & AI Optimization", style='Normal')
    subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_para.style.font.size = Pt(16)
    subtitle_para.style.font.color.rgb = RGBColor(100, 100, 100)
    
    doc.add_paragraph()
    doc.add_paragraph()
    
    date_para = doc.add_paragraph(datetime.now().strftime("%B %d, %Y"))
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.style.font.bold = True
    
    doc.add_paragraph()
    conf_para = doc.add_paragraph("CONFIDENTIAL - INTERNAL USE ONLY")
    conf_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    conf_para.style.font.size = Pt(9)
    conf_para.style.font.color.rgb = RGBColor(200, 0, 0)

    doc.add_page_break()

    # --- Content Parsing ---
    # Simple Markdown Parser
    lines = strategy_content.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('# '):
            doc.add_paragraph(line[2:], style='Heading 1')
        elif line.startswith('## '):
            doc.add_paragraph(line[3:], style='Heading 2')
        elif line.startswith('### '):
            doc.add_paragraph(line[4:], style='Heading 3')
        elif line.startswith('- ') or line.startswith('* '):
            p = doc.add_paragraph(line[2:], style='List Bullet')
            apply_formatting(p, line[2:])
        elif re.match(r'^\d+\.', line):
            # Ordered list
            text_part = re.sub(r'^\d+\.\s*', '', line)
            p = doc.add_paragraph(text_part, style='List Number')
            apply_formatting(p, text_part)
        else:
            p = doc.add_paragraph(style='Normal')
            apply_formatting(p, line)

    # --- Footer ---
    # Add page numbers or footer text
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "Generated by AI Strategy Crew"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    footer_para.style.font.size = Pt(8)
    footer_para.style.font.color.rgb = RGBColor(150, 150, 150)

    # Save to buffer
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream

def apply_formatting(paragraph, text):
    """
    Apply bold/italic formatting to a paragraph.
    Note: This is a simplified parser. It replaces the entire text of the paragraph 
    handling **bold** segments crudely by splitting. 
    """
    # Clear existing runs (created during add_paragraph)
    paragraph.clear()
    
    # Split by bold markers
    parts = re.split(r'(\*\*.*?\*\*)', text)
    
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)
